--------------------------------------------------------
-- Archivo creado  - miércoles-febrero-10-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ADMIN_USUARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "CNP_INSCRIPCION_WEB"."SEQ_ADMIN_USUARIOS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FORM_NOACEPTO
--------------------------------------------------------

   CREATE SEQUENCE  "CNP_INSCRIPCION_WEB"."SEQ_FORM_NOACEPTO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FORM_PREREGISTRO
--------------------------------------------------------

   CREATE SEQUENCE  "CNP_INSCRIPCION_WEB"."SEQ_FORM_PREREGISTRO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PREREGISTRO_PERSONAS
--------------------------------------------------------

   CREATE SEQUENCE  "CNP_INSCRIPCION_WEB"."SEQ_PREREGISTRO_PERSONAS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CNP_ADMIN_USUARIOS
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS" 
   (	"ID_USUARIOS" NUMBER, 
	"USUARIO" VARCHAR2(50 BYTE), 
	"CLAVE" VARCHAR2(200 BYTE), 
	"TIPO_USUARIO" VARCHAR2(2 BYTE), 
	"ESTADO" VARCHAR2(2 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_EXPIRACION" VARCHAR2(20 BYTE), 
	"NRO_ENCUESTA_FORM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS"."ID_USUARIOS" IS 'id de la tabla';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS"."USUARIO" IS 'usuario para el acceso (correo Electronico)';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS"."CLAVE" IS 'Clave de acceso';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS"."TIPO_USUARIO" IS 'Tipo de usuario F fuente ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS"."ESTADO" IS '1 = activio ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS"."FECHA_CREACION" IS 'Fecha de creacion';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS"."FECHA_EXPIRACION" IS 'Fecha de expiracion';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS"."NRO_ENCUESTA_FORM" IS 'Numero de formulario asignado';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS"  IS 'Tabla de Usuarios para el ingreso al eCENSO';
--------------------------------------------------------
--  DDL for Table CNP_ADMIN_USUARIOS_ADM
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" 
   (	"ID_USUARIOS_ADM" NUMBER, 
	"USUARIO" VARCHAR2(50 BYTE), 
	"CLAVE" VARCHAR2(200 BYTE), 
	"TIPO_USUARIO" VARCHAR2(2 BYTE), 
	"ESTADO" VARCHAR2(2 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_EXPIRACION" VARCHAR2(20 BYTE), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM"."ID_USUARIOS_ADM" IS 'id de la tabla';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM"."USUARIO" IS 'usuario para el acceso (correo Electronico)';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM"."CLAVE" IS 'Clave de acceso';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM"."TIPO_USUARIO" IS 'Tipo de usuario. A: Administrador';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM"."ESTADO" IS '1 = activo; 0= inactivo';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM"."FECHA_CREACION" IS 'Fecha de creacion';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM"."FECHA_EXPIRACION" IS 'Fecha de expiracion';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM"."NOMBRES" IS 'Nombres del Usuario';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM"."APELLIDOS" IS 'Apellidos del usuario';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM"  IS 'Tabla de Usuarios Administradores del ecenso';
--------------------------------------------------------
--  DDL for Table CNP_DOMINIO
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNP_DOMINIO" 
   (	"ID_DOMINIO" NUMBER, 
	"DESCRIPCION" VARCHAR2(40 BYTE), 
	"PREGUNTA_ASOCIADA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_DOMINIO"."ID_DOMINIO" IS 'Identificador único por dominio';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_DOMINIO"."DESCRIPCION" IS 'Nombre del dominio';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_DOMINIO"."PREGUNTA_ASOCIADA" IS 'Preguntas en las que se usa el dominio';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNP_DOMINIO"  IS 'Tabla con los nombres de cada dominio';
--------------------------------------------------------
--  DDL for Table CNP_NOACEPTO
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNP_NOACEPTO" 
   (	"DIRECTORIO" VARCHAR2(40 BYTE), 
	"OBS" VARCHAR2(2000 BYTE), 
	"FECHA" DATE DEFAULT SYSDATE, 
	"NRO_ENCUESTA_FORM" NUMBER(*,0), 
	"OPCION" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_NOACEPTO"."DIRECTORIO" IS 'id tabla';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_NOACEPTO"."OBS" IS 'observaciones del usuario';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_NOACEPTO"."FECHA" IS 'fecha de ingreso';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_NOACEPTO"."NRO_ENCUESTA_FORM" IS 'numero de formulario asignado';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_NOACEPTO"."OPCION" IS 'opcion seleccionada del porque no acepta';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNP_NOACEPTO"  IS 'Tabla de personas que no aceptaron diligenciar el formulario de inscripcion';
--------------------------------------------------------
--  DDL for Table CNP_PREREGISTRO
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO" 
   (	"DIRECTORIO" VARCHAR2(40 BYTE), 
	"PRIMER_NOMBRE" VARCHAR2(100 BYTE), 
	"SEGUNDO_NOMBRE" VARCHAR2(100 BYTE), 
	"PRIMER_APELLIDO" VARCHAR2(100 BYTE), 
	"SEGUNDO_APELLIDO" VARCHAR2(100 BYTE), 
	"C4P40_TIPO_DOC" VARCHAR2(10 BYTE), 
	"CEDULA" VARCHAR2(20 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(50 BYTE), 
	"INDICATIVO" VARCHAR2(5 BYTE), 
	"TEL_FIJO" VARCHAR2(15 BYTE), 
	"TEL_CELULAR" VARCHAR2(15 BYTE), 
	"C1I1_DPTO" VARCHAR2(5 BYTE), 
	"C1I2_MPIO" VARCHAR2(5 BYTE), 
	"C1IV10_DIR" VARCHAR2(150 BYTE), 
	"CLASE" VARCHAR2(200 BYTE), 
	"LOCALIDAD_COMUNA" VARCHAR2(200 BYTE), 
	"CENTRO_POBLADO" VARCHAR2(200 BYTE), 
	"BARRIO_CORREGI_VEREDA" VARCHAR2(200 BYTE), 
	"C3H_TOT_PER" VARCHAR2(5 BYTE), 
	"FECHA" DATE DEFAULT SYSDATE, 
	"CONTRASENA" VARCHAR2(20 BYTE), 
	"FECHAFIN" DATE, 
	"NRO_ENCUESTA_FORM" NUMBER(*,0), 
	"TERRITORIALIDAD_ETNICA" VARCHAR2(500 BYTE), 
	"NOM_RESGUARDO_INDIGENA" VARCHAR2(500 BYTE), 
	"NOM_COMUNIDAD_NEGRA" VARCHAR2(500 BYTE), 
	"COMUNIDAD_VEREDA_RANCHERIA" VARCHAR2(500 BYTE), 
	"NOM_COMUNIDAD_VEREDA_RANCHERIA" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."DIRECTORIO" IS 'Número consecutivo';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."PRIMER_NOMBRE" IS 'Primer nombre de la persona que realiza la inscripción';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."SEGUNDO_NOMBRE" IS 'Segundo nombre de la persona que realiza la inscripción';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."PRIMER_APELLIDO" IS 'Primer apellido de la persona que realiza la inscripción';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."SEGUNDO_APELLIDO" IS 'Segundo apellido de la persona que realiza la inscripción';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."C4P40_TIPO_DOC" IS 'Tipo del documento de identidad de la persona que realiza la inscripción
1: Registro civil
2: Tarjeta Identidad
3. Cedula de ciudadania
4. Cedula extranjeria
5. No sabe';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."CEDULA" IS 'Número de documento de la persona que realiza la inscripción';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."CORREO_ELECTRONICO" IS 'Correo electrónico de la persona que realiza la inscripción';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."INDICATIVO" IS 'Indicativo del número telefónico local';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."TEL_FIJO" IS 'Número telefónico fijo o de contacto';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."TEL_CELULAR" IS 'Número celular de la persona que realiza la inscripción';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."C1I1_DPTO" IS 'Código del departamento donde reside la persona';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."C1I2_MPIO" IS 'Código del municipio donde reside la persona';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."C1IV10_DIR" IS 'Dirección donde reside la persona';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."CLASE" IS 'Latitud entregada por la DIG';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."LOCALIDAD_COMUNA" IS 'Longitud entregada por la DIG';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."CENTRO_POBLADO" IS 'Código DANE entregado por la DIG';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."BARRIO_CORREGI_VEREDA" IS 'Destino entregado por la DIG';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."C3H_TOT_PER" IS 'Total de personas';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."FECHA" IS 'Fecha de registro inicial';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."CONTRASENA" IS 'Contraseña asignada por el usuario para el formulario general';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."FECHAFIN" IS 'Fecha de registro final';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."NRO_ENCUESTA_FORM" IS 'Número del formulario asignado al usuario para el censo';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"."TERRITORIALIDAD_ETNICA" IS 'Dirección de google entregada por la DIG';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO"  IS 'Tabla de las personas que diligenciaron el formulario de inscripcion del ecenso';
--------------------------------------------------------
--  DDL for Table CNP_PREREGISTRO_PERSONAS
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS" 
   (	"DIRECTORIO" VARCHAR2(40 BYTE), 
	"C4P40_TIPO_DOC" VARCHAR2(5 BYTE), 
	"C4P41_SABE_DOC" VARCHAR2(100 BYTE), 
	"C4P39A_1ER_NOMBRE" VARCHAR2(100 BYTE), 
	"C4P39AA_2DO_NOMBRE" VARCHAR2(100 BYTE), 
	"C4P39B_1ER_APELLIDO" VARCHAR2(100 BYTE), 
	"C4P39BB_2DO_APELLIDO" VARCHAR2(100 BYTE), 
	"C4P44_EDAD" VARCHAR2(5 BYTE), 
	"C4P42_SEXO" VARCHAR2(5 BYTE), 
	"JEFE" NUMBER, 
	"NRO_ENCUESTA_FORM" NUMBER(*,0), 
	"COMPLETO" NUMBER, 
	"C4P41_NRO_PER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."DIRECTORIO" IS 'id de la tabla';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."C4P40_TIPO_DOC" IS 'tipo de documento del integrante del hogar
1: Registro civil
2: Tarjeta Identidad
3. Cedula de ciudadania
4. Cedula extranjeria
5. No sabe';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."C4P41_SABE_DOC" IS 'numero de documento del integrante del hogar';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."C4P39A_1ER_NOMBRE" IS 'primer nombre del integrante del hogar ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."C4P39AA_2DO_NOMBRE" IS 'segundo nombre del integrante del hogar ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."C4P39B_1ER_APELLIDO" IS 'primer apellido del integrante del hogar ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."C4P39BB_2DO_APELLIDO" IS 'segundo apellido del integrante del hogar ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."C4P44_EDAD" IS 'edad del integrante del hogar';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."C4P42_SEXO" IS 'sexo del integrante del hogar';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."JEFE" IS 'jefe del hogar 1 si 2 no';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."NRO_ENCUESTA_FORM" IS 'numero de formulario al que pertenece la persona';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"."COMPLETO" IS 'estado de la persona, 1 completo 0 incompleto';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS"  IS 'Tabla de los integrantes del hogar';
--------------------------------------------------------
--  DDL for Table CNP_RESPUESTA_DOMINIO
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO" 
   (	"ID_RESPUESTA_DOMINIO" NUMBER, 
	"ID_DOMINIO" NUMBER, 
	"VALOR_MINIMO" VARCHAR2(6 BYTE), 
	"VALOR_MAXIMO" VARCHAR2(6 BYTE), 
	"DESCRIPCION" VARCHAR2(250 BYTE), 
	"ID_RESPUESTA_DOMINIO_PADRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO"."ID_RESPUESTA_DOMINIO" IS 'Identificador único de la tabla CNP_RESPUESTA_DOMINIO';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO"."ID_DOMINIO" IS 'Identificador único de la tabla CNP_DOMINIO al que se encuentra asociado el ítem';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO"."VALOR_MINIMO" IS 'Valor mínimo del dominio. No puede ser nulo';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO"."VALOR_MAXIMO" IS 'Valor máximo del dominio. Puede no existir para los ítems del dominio';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO"."DESCRIPCION" IS 'Descripción del ítem dentro del dominio';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO"."ID_RESPUESTA_DOMINIO_PADRE" IS '';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO"  IS 'Tabla con los ítems o respuestas que componen cada dominio';
--------------------------------------------------------
--  DDL for Table CNPV_ADMIN_CONTROL
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL" 
   (	"NRO_ENCUESTA_FORM" NUMBER(*,0), 
	"SEC_PREREG" NUMBER, 
	"SEC_VIVI" NUMBER(*,0), 
	"SEC_HOGAR" NUMBER(*,0), 
	"SEC_PERS" NUMBER(*,0), 
	"FEC_INIPREREG" DATE, 
	"FEC_FINPREREG" DATE, 
	"FEC_INICENSO" DATE, 
	"FEC_FINCENSO" DATE, 
	"FK_ESTADO" NUMBER, 
	"FK_DEPTO" NUMBER, 
	"FK_MPIO" NUMBER, 
	"SEC_ENCU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL"."SEC_ENCU" IS 'Estado de diligenciamiento de la encuesta final de envio.';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL"  IS 'Tabla con de control para la administración de usuarios';
--------------------------------------------------------
--  DDL for Table CNPV_DIVIPOLA
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_DIVIPOLA" 
   (	"C_DPTO" VARCHAR2(2 BYTE), 
	"C_MPIO" VARCHAR2(5 BYTE), 
	"DPTO" VARCHAR2(80 BYTE), 
	"MPIO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_DIVIPOLA"  IS 'Tabla con la información de parámetros de la División Política del territorio';
--------------------------------------------------------
--  DDL for Table CNPV_ENCUESTA_FINAL
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL" 
   (	"NRO_ENCUESTA_FORM" NUMBER, 
	"INSCRIP" NUMBER(1,0), 
	"INSCRIP_INCONV" NUMBER(1,0), 
	"INSCRIP_INCONV_CUAL" VARCHAR2(1000 BYTE), 
	"INSCRIP_RECOMEND" VARCHAR2(1000 BYTE), 
	"DILIG" NUMBER(1,0), 
	"DILIG_PREG" NUMBER(1,0), 
	"DILIG_INCONV" NUMBER(1,0), 
	"DILIG_INCONV_CUAL" VARCHAR2(1000 BYTE), 
	"DILIG_RECOMEND" VARCHAR2(1000 BYTE), 
	"SOPORTE" NUMBER(1,0), 
	"CHAT_ATEN" NUMBER(1,0), 
	"CHAT_RAPID" NUMBER(1,0), 
	"CHAT_SOLUC" NUMBER(1,0), 
	"CHAT_PERS" NUMBER(1,0), 
	"TEL_ATEN" NUMBER(1,0), 
	"TEL_RAPID" NUMBER(1,0), 
	"TEL_SOLUC" NUMBER(1,0), 
	"TEL_PERS" NUMBER(1,0), 
	"EMAIL_ATEN" NUMBER(1,0), 
	"EMAIL_RAPID" NUMBER(1,0), 
	"EMAIL_SOLUC" NUMBER(1,0), 
	"EMAIL_PERS" NUMBER(1,0), 
	"FK_USU_DIGITA" NUMBER, 
	"FECHA_DIGITACION" TIMESTAMP (1) WITH LOCAL TIME ZONE, 
	"SOPORT_RECOMEND" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."NRO_ENCUESTA_FORM" IS 'Id de la encuesta, se relaciona con tabla control.';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."INSCRIP" IS 'Considera que el proceso de inscripcion fue';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."INSCRIP_INCONV" IS 'Tuvo algun inconveniente durante el proceso de inscripcion';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."INSCRIP_INCONV_CUAL" IS 'Cual inconveniente durante el proceso de inscripcion';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."INSCRIP_RECOMEND" IS 'Tiene alguna recomendacion para mejorar el proceso de inscripcion';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."DILIG" IS 'Considera que el cuestionario de Diligenciamiento fue.';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."DILIG_PREG" IS 'Considera que las preguntas del cuestionario fueron:
';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."DILIG_INCONV" IS 'Tuvo algun inconveniente durante el diligenciamiento ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."DILIG_INCONV_CUAL" IS 'Cual  inconveniente tuvo durante el diligenciamiento ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."DILIG_RECOMEND" IS 'Tiene alguna recomendacion para mejorar el proceso de diligenciamiento ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."SOPORTE" IS 'Utilizo algunos de los canales de soporte ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."CHAT_ATEN" IS 'Chat - Atención a la inquietud';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."CHAT_RAPID" IS 'Chat -Rapidez de la respuesta';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."CHAT_SOLUC" IS 'Chat -Solución de la inquietud';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."CHAT_PERS" IS 'Chat -La atención del personal';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."TEL_ATEN" IS 'Tel  - Atención a la inquietud';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."TEL_RAPID" IS 'Tel - Rapidez de la respuesta';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."TEL_SOLUC" IS 'Tel - Solución de la inquietud';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."TEL_PERS" IS 'Tel -La atención del personal';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."EMAIL_ATEN" IS 'Email  - Atención a la inquietud';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."EMAIL_RAPID" IS 'Email  - Rapidez de la respuesta';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."EMAIL_SOLUC" IS 'Email - Solución de la inquietud';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."EMAIL_PERS" IS 'Email - La atencion del personal ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."FK_USU_DIGITA" IS 'Usuario que digita encuesta';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."FECHA_DIGITACION" IS 'Fecha y hora en que guarda';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"."SOPORT_RECOMEND" IS 'Tiene alguna recomendacion para mejorar el servicio de soporte';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL"  IS 'Se guarda el diligenciamiento de la encuesta final.';
--------------------------------------------------------
--  DDL for Table CNPV_HOGAR
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_HOGAR" 
   (	"C0I1_ENCUESTA" NUMBER(9,0), 
	"C3H24_NROHOG" NUMBER(2,0), 
	"C3H_TOT_PER" NUMBER(2,0), 
	"C3H25_VIVE_EN" NUMBER(1,0), 
	"C3H26_VR_ARRDO" NUMBER(8,0), 
	"C3H27_NRO_CUARTOS" NUMBER(2,0), 
	"C3H28_NRO_DORMIT" NUMBER(2,0), 
	"C3H29_COCINAN_CON" NUMBER(1,0), 
	"C3H30_OTRO_COMB" NUMBER(1,0), 
	"C3H30A_CUAL_OTRO" NUMBER(1,0), 
	"C3H31_AGUA_COCIN" NUMBER(2,0), 
	"C3H32_RECICLAN" NUMBER(1,0), 
	"C3H33A_RADIO" NUMBER(1,0), 
	"C3H33B_TVABIE" NUMBER(1,0), 
	"C3H33C_TVSUSC" NUMBER(1,0), 
	"C3H33D_TEL_FIJO" NUMBER(1,0), 
	"C3H33E_INT_FIJO" NUMBER(1,0), 
	"C3H33F_INT_MOVIL" NUMBER(1,0), 
	"C3H33G_PC" NUMBER(1,0), 
	"C3H34_EMIGRA" NUMBER(1,0), 
	"C3H34A_VENEZUELA" NUMBER(1,0), 
	"C3H34B_USA" NUMBER(1,0), 
	"C3H34C_ESPANA" NUMBER(1,0), 
	"C3H34D_ECUADOR" NUMBER(1,0), 
	"C3H34E_PANAMA" NUMBER(1,0), 
	"C3H34F_CANADA" NUMBER(1,0), 
	"C3H34G_OTRO_PAIS" NUMBER(1,0), 
	"C3H34G1_OTRO_CUAL" VARCHAR2(30 BYTE), 
	"C3H35_NRO_FALL" NUMBER(2,0), 
	"C3H36_AE_HOG" NUMBER(1,0), 
	"C3H36A_AE_GRUPO" NUMBER(2,0), 
	"C3H36B_AE_REALIZA" NUMBER(2,0), 
	"C3H36C_AE_QPER" NUMBER(2,0), 
	"C3H37A_DESPLAFORZ" NUMBER(1,0), 
	"C3H37A1_ANIODESPLA" NUMBER(4,0), 
	"C3H37A2_RETORNO" NUMBER(1,0), 
	"C3H37B_DESPLAFORZ" NUMBER(1,0), 
	"C3H37B1_ANIODESPLA" NUMBER(4,0), 
	"C3H37B2_RETORNO" NUMBER(1,0), 
	"C3H37C_DESPLAFORZ" NUMBER(1,0), 
	"C3H37C1_ANIODESPLA" NUMBER(4,0), 
	"C3H37C2_RETORNO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C0I1_ENCUESTA" IS 'C0I1_Numero de Encuesta                   (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H24_NROHOG" IS 'C3H24_Número de orden del Hogar dentro de la vi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H_TOT_PER" IS 'C3H_Total personas hogar                       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H25_VIVE_EN" IS 'C3H25_La vivienda ocupada por este hogar es:   ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H26_VR_ARRDO" IS 'C3H26_¿Cuanto paga o pagaría si tuviera que hac';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H27_NRO_CUARTOS" IS 'C3H27_Incluidos la sala y el comedor, ¿de CUANT';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H28_NRO_DORMIT" IS 'C3H28_¿CUANTOS de esos cuartos usan para dormir';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H29_COCINAN_CON" IS 'C3H29_¿Con qué energía o combustible cocinal PR';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H30_OTRO_COMB" IS 'C3H30_Adicionalmente, ¿Utililzan otro combustib';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H30A_CUAL_OTRO" IS 'C3H30A_¿Cual otro combustible?                 ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H31_AGUA_COCIN" IS 'C3H31_¿De dónde obtiene PRINCIPALMENTE este hog';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H32_RECICLAN" IS 'C3H32_¿En este hogar separan los residuos sólid';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H33A_RADIO" IS 'C3H33A_¿Este hogar DISPONE de: Señal de Radio  ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H33B_TVABIE" IS 'C3H33B_¿Este hogar DISPONE de: servicio de tele';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H33C_TVSUSC" IS 'C3H33C_¿Este hogar DISPONE de: Servicio de tele';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H33D_TEL_FIJO" IS 'C3H33D_¿Este hogar DISPONE de: Línea telefonica';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H33E_INT_FIJO" IS 'C3H33E_¿Este hogar DISPONE de: Acceso a interne';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H33F_INT_MOVIL" IS 'C3H33F_¿Este hogar DISPONE de: Acceso a interne';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H33G_PC" IS 'C3H33G_¿Este hogar DISPONE de: Computador      ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H34_EMIGRA" IS 'C3H34_Durante los ultimos 5 años(Agosto 2011 a ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H34A_VENEZUELA" IS 'C3H34A_¿En que país(es) vive(n)  actualmente? V';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H34B_USA" IS 'C3H34B_¿En que país(es) vive(n) actualmente? Es';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H34C_ESPANA" IS 'C3H34C_¿En que país(es) vive(n) actualmente? Es';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H34D_ECUADOR" IS 'C3H34D_¿En que país(es) vive(n) actualmente? Ec';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H34E_PANAMA" IS 'C3H34E_¿En que país(es) vive(n) actualmente? Pa';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H34F_CANADA" IS 'C3H34F_¿En que país(es) vive(n) actualmente? Ca';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H34G_OTRO_PAIS" IS 'C3H34G_¿En que país(es)  actualmente? Otro país';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H34G1_OTRO_CUAL" IS 'C3H34G1_Otro país ¿Cual?                       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H35_NRO_FALL" IS 'C3H35_¿Cuantas personas que ERAN MIEMBROS de es';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H36_AE_HOG" IS 'C3H36_¿Durante los últimos 30 días, algún miemb';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H36A_AE_GRUPO" IS 'C3H36A_¿Cual actividad? (Si se realizan 2 o más';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H36B_AE_REALIZA" IS 'C3H36B_El código que acabó de marcar, ubíquelo ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H36C_AE_QPER" IS 'C3H36C_¿Cuantas personas trabajaron en los ulti';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H37A_DESPLAFORZ" IS 'C3H37A_¿Usted o algún miembro de su hogar ha vi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H37A1_ANIODESPLA" IS 'C3H37A1_¿Año del desplazamiento Forzado?       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H37A2_RETORNO" IS 'C3H37A2_¿Ha(n) retornado a la residencia de la ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H37B_DESPLAFORZ" IS 'C3H37B_¿Usted o algún miembro de su hogar ha vi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H37B1_ANIODESPLA" IS 'C3H37B1_¿Año del abandono forzado de tierras?  ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H37B2_RETORNO" IS 'C3H37B2_¿Ha(n) retornado a la residencia de la ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H37C_DESPLAFORZ" IS 'C3H37C_¿Usted o algún miembro de su hogar ha vi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H37C1_ANIODESPLA" IS 'C3H37C1_¿Año del despojo de tierras?           ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"."C3H37C2_RETORNO" IS 'C3H37C2_¿Ha(n) retornado a la residencia de la ';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_HOGAR"  IS 'Tabla con la información por hogar de la encuesta';
--------------------------------------------------------
--  DDL for Table CNPV_PARAM_CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_CATEGORIAS" 
   (	"ID_CATEGORIA" NUMBER(*,0), 
	"DESCRIPCION_CATEGORIA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_CATEGORIAS"."ID_CATEGORIA" IS 'Id de la categoria';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_CATEGORIAS"."DESCRIPCION_CATEGORIA" IS 'Descripción de la categoria';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_CATEGORIAS"  IS 'tabla de categorias de los primeros 7000 mail enviados';
--------------------------------------------------------
--  DDL for Table CNPV_PARAM_ESTADOS
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_ESTADOS" 
   (	"ID_ESTADO" NUMBER, 
	"DESC_ESTADO" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_ESTADOS"."ID_ESTADO" IS 'id de la categoria';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_ESTADOS"."DESC_ESTADO" IS 'descripcion de la categoria';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_ESTADOS"  IS 'Tabla de estados del formulario ';
--------------------------------------------------------
--  DDL for Table CNPV_PARAM_MUESTRA
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA" 
   (	"CEDULA" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(50 BYTE), 
	"CODMPIO" NUMBER(*,0), 
	"CATEGORIA" NUMBER(*,0), 
	"LIBRO" VARCHAR2(100 BYTE), 
	"SEXO" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA"."CEDULA" IS 'numero del documento de identidad del servidor';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA"."NOMBRE" IS 'nombre del servidor';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA"."CORREO_ELECTRONICO" IS 'email del servidor';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA"."CODMPIO" IS 'municipio del servidor';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA"."CATEGORIA" IS 'codigo de la tabla de cnpv_param_categorias';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA"."LIBRO" IS 'libro del servidor';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA"."SEXO" IS 'genero del servidor';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA"  IS 'Tabla con la muestra de los primeros 7000 correos enviados';
--------------------------------------------------------
--  DDL for Table CNPV_PARAM_PAIS
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_PAIS" 
   (	"ID_PAIS" NUMBER(*,0), 
	"NOMBRE_PAIS" VARCHAR2(250 BYTE), 
	"CODIGO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_PAIS"."ID_PAIS" IS 'Consecutivo de la tabla';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_PAIS"."NOMBRE_PAIS" IS 'Nombre del país';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PARAM_PAIS"."CODIGO" IS 'Código del país';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_PAIS"  IS 'Tabla parametrica de paises ';
--------------------------------------------------------
--  DDL for Table CNPV_PERSONA_FALLECIDA
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA" 
   (	"C0I1_ENCUESTA" NUMBER(9,0), 
	"C3F24_NROHOG" NUMBER(2,0), 
	"C3F35A_NRO_FALL" NUMBER(2,0), 
	"C3F35B_SEXO_FALL" NUMBER(1,0), 
	"C3F35C_EDAD_FALL" NUMBER(3,0), 
	"C3F35D_CERT_DEFUN" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA"."C0I1_ENCUESTA" IS 'C0I1_Numero de Encuesta                   (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA"."C3F24_NROHOG" IS 'C3F24_Número de orden del Hogar dentro de la vi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA"."C3F35A_NRO_FALL" IS 'C3F35A_Número orden persona fallecida          ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA"."C3F35B_SEXO_FALL" IS 'C3F35B_Sexo Fallecido                          ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA"."C3F35C_EDAD_FALL" IS 'C3F35C_Edad al morir                           ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA"."C3F35D_CERT_DEFUN" IS 'C3F35D_¿Se expidió certificado médico de defunc';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA"  IS 'Tabla con la información de las personas fallecidas por hogar';
--------------------------------------------------------
--  DDL for Table CNPV_PERSONA_HOGAR
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR" 
   (	"C0I1_ENCUESTA" NUMBER(9,0), 
	"C3P24_NROHOG" NUMBER(2,0), 
	"C4P41_NRO_PER" NUMBER(2,0), 
	"C4P42A_1ER_NOMBRE" VARCHAR2(15 BYTE), 
	"C4P42B_1ER_APELLIDO" VARCHAR2(15 BYTE), 
	"C4P43_TIPO_DOC" NUMBER(1,0), 
	"C4P44_SABE_DOC" NUMBER(1,0), 
	"C4P44_NRO_DOC" VARCHAR2(14 BYTE), 
	"C4P45_SEXO" NUMBER(1,0), 
	"C4P46_SABE_FECHA" NUMBER(1,0), 
	"C4P46A_DIA_NAC" NUMBER(2,0), 
	"C4P46B_MES_NAC" NUMBER(2,0), 
	"C4P46C_ANO_NAC" NUMBER(4,0), 
	"C4P47_EDAD" NUMBER(3,0), 
	"C4P48_COLOMBIA" NUMBER(1,0), 
	"C4P48A_OTRA" NUMBER(1,0), 
	"C4P48B_CUAL_NAL" VARCHAR2(20 BYTE), 
	"C4P49_PARENTESCO" NUMBER(2,0), 
	"C4P50_LUG_NAC" NUMBER(1,0), 
	"C4P50A_DPTO_NAC" NUMBER(2,0), 
	"C4P50B_MPIO_NAC" NUMBER(5,0), 
	"C4P50C_PAIS_NAC" NUMBER(3,0), 
	"C4P50C1_ANO_LLEGO" NUMBER(4,0), 
	"C4P51_RES_MAMA" NUMBER(1,0), 
	"C4P51A_DPTO_MAMA" NUMBER(2,0), 
	"C4P51B_MPIO_MAMA" NUMBER(5,0), 
	"C4P51C_PAIS_MAMA" NUMBER(3,0), 
	"C4P52_VIVIA_5ANOS" NUMBER(1,0), 
	"C4P52A_DPTO_5ANOS" NUMBER(2,0), 
	"C4P52B_MPIO_5ANOS" NUMBER(5,0), 
	"C4P52C_PAIS_5ANO" NUMBER(3,0), 
	"C4P52C1_ANO_LLEGA5" NUMBER(4,0), 
	"C4P53_CLASE_5ANOS" NUMBER(1,0), 
	"C4P54_VIVIA_1ANO" NUMBER(1,0), 
	"C4P54A_DPTO_1ANO" NUMBER(2,0), 
	"C4P54B_MPIO_1ANO" NUMBER(5,0), 
	"C4P54C_PAIS_1ANO" NUMBER(3,0), 
	"C4P55_CLASE_1ANO" NUMBER(1,0), 
	"C4P56_CAUSA_1ANO" NUMBER(2,0), 
	"C4P56A_OTRA_CAUSA" VARCHAR2(30 BYTE), 
	"C4P57_ETNIA" NUMBER(1,0), 
	"C4P57A_COD_ETNIA" NUMBER(3,0), 
	"C4P58A_HABLA_LENG" NUMBER(1,0), 
	"C4P58B_OTRAS_LENG" NUMBER(1,0), 
	"C4P58B1_QOTRAS_LENG" NUMBER(1,0), 
	"C4P58C_HABLA_ESP" NUMBER(1,0), 
	"C4P59_CREENCIA" NUMBER(1,0), 
	"C4P60_AFI_SALUD" NUMBER(1,0), 
	"C4P60A_REGIMEN" NUMBER(1,0), 
	"C4P61_ENFERMO" NUMBER(1,0), 
	"C4P62A_HOSPITAL" NUMBER(1,0), 
	"C4P62B_MED_TRAD" NUMBER(1,0), 
	"C4P63_ATENDIERON" NUMBER(1,0), 
	"C4P64A_OIR" NUMBER(1,0), 
	"C4P64B_HABLAR" NUMBER(1,0), 
	"C4P64C_VER" NUMBER(1,0), 
	"C4P64D_CAMINAR" NUMBER(1,0), 
	"C4P64E_COGER" NUMBER(1,0), 
	"C4P64F_DECIDIR" NUMBER(1,0), 
	"C4P64G_COMER" NUMBER(1,0), 
	"C4P64H_RELACION" NUMBER(1,0), 
	"C4P64I_TAREAS" NUMBER(1,0), 
	"C4P65_LIM_PPAL" VARCHAR2(1 BYTE), 
	"C4P66_CAUSA" NUMBER(1,0), 
	"C4P66A_OTRACAUSA" VARCHAR2(30 BYTE), 
	"C4P67A_AYUDA_TEC" NUMBER(1,0), 
	"C4P67B_AYUDA_PERS" NUMBER(1,0), 
	"C4P67C_AYUDA_MED" NUMBER(1,0), 
	"C4P67D_AYUDA_ANCES" NUMBER(1,0), 
	"C4P67E_AYUDA_ANIM" NUMBER(1,0), 
	"C4P67F_AYUDA_OTRO" NUMBER(1,0), 
	"C4P68_CUIDA" NUMBER(1,0), 
	"C4P69_ESTAB_ASIS" NUMBER(1,0), 
	"C4P70_EDU_INTEG" NUMBER(1,0), 
	"C4P71_ALFABETA" NUMBER(1,0), 
	"C4P72_ASISTENCIA" NUMBER(1,0), 
	"C4P72A_UBIC_INST" NUMBER(1,0), 
	"C4P72A1_DPTO_INST" NUMBER(2,0), 
	"C4P72A2_MPIO_INST" NUMBER(5,0), 
	"C4P72A3_PAIS_INST" NUMBER(3,0), 
	"C4P72B_DEJO_EST" NUMBER(1,0), 
	"CAP72C1_FAMILIA" NUMBER(2,0), 
	"CAP72C2_ECONOMIA" NUMBER(2,0), 
	"CAP72C3_INSTEDUC" NUMBER(2,0), 
	"CAP72C4_EDUCANT" NUMBER(2,0), 
	"CAP72C5_ENTORNOEDUC" NUMBER(2,0), 
	"CAP72C6_PERSONAL" NUMBER(2,0), 
	"CAP72C7_OTRA" VARCHAR2(45 BYTE), 
	"C4P73_NIVEL_ANOS" NUMBER(2,0), 
	"C4P74A_CEL" NUMBER(1,0), 
	"C4P74B_PC" NUMBER(1,0), 
	"C4P74C_TABLETA" NUMBER(1,0), 
	"C4P74D_INTERNET" NUMBER(1,0), 
	"C4P75_TRABAJO" NUMBER(1,0), 
	"CAP76A_NEG_FLIA" NUMBER(1,0), 
	"CAP76B_NEG_FLIG" NUMBER(1,0), 
	"CAP76C_NEG_FLIF" NUMBER(1,0), 
	"CAP76D_NEG_FLIE" NUMBER(1,0), 
	"CAP76E_NEG_FLID" NUMBER(1,0), 
	"CAP76F_NEG_FLIC" NUMBER(1,0), 
	"CAP76G_NEG_FLIB" NUMBER(1,0), 
	"CAP77_AE_EMPRESA" NUMBER(2,0), 
	"CAP77A_AE_REALIZA" NUMBER(2,0), 
	"C4P78_TIPO_TRAB" NUMBER(1,0), 
	"C4P79_SITIO_TRAB" NUMBER(1,0), 
	"C4P79A_DPTO_TRAB" NUMBER(2,0), 
	"C4P79B_MPIO_TRAB" NUMBER(5,0), 
	"C4P79C_PAIS_TRAB" NUMBER(3,0), 
	"C4P80_COTIZ_PENS" NUMBER(1,0), 
	"C4P81_EST_CIVIL" NUMBER(1,0), 
	"C4P82_THNV" NUMBER(2,0), 
	"C4P82A_HNVH" NUMBER(2,0), 
	"C4P82B_HNVM" NUMBER(2,0), 
	"C4P83_HNV" NUMBER(1,0), 
	"C4P83A_THSV" NUMBER(2,0), 
	"C4P83B_HSVH" NUMBER(2,0), 
	"C4P83C_HSVM" NUMBER(2,0), 
	"C4P84_HFC" NUMBER(1,0), 
	"C4P84A_THFC" NUMBER(2,0), 
	"C4P84B_HFCH" NUMBER(2,0), 
	"C4P84C_HFCM" NUMBER(2,0), 
	"C4P85_UHVA" NUMBER(1,0), 
	"C4P86A_DIA_UHVA" NUMBER(2,0), 
	"C4P86B_MES_UHVA" NUMBER(2,0), 
	"C4P86C_ANO_UHVA" NUMBER(4,0), 
	"CAP87_ORI_SEX" NUMBER(1,0), 
	"CAP88_REC_GENERO" NUMBER(1,0), 
	"C4P89_FUE_CENS" NUMBER(1,0), 
	"C4P90_LUG_CENS" NUMBER(1,0), 
	"C4P90A_DPTO_CENS" NUMBER(2,0), 
	"C4P90B_MPIO_CENS" NUMBER(5,0), 
	"C4P91_MES_CENS" NUMBER(2,0), 
	"PERSONA_HOGAR_CCNTROL" NUMBER(2,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C0I1_ENCUESTA" IS 'C0I1_Numero de Encuesta                   (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C3P24_NROHOG" IS 'C3P24_Número de orden del Hogar dentro de la vi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P41_NRO_PER" IS 'C4P41_Número orden persona                     ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P42A_1ER_NOMBRE" IS 'C4P42A_Primer nombre de la persona             ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P42B_1ER_APELLIDO" IS 'C4P42B_Primer apellido de la persona           ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P43_TIPO_DOC" IS 'C4P43_¿Que tipo de documento de identidad tiene';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P44_SABE_DOC" IS 'C4P44_¿Sabe cual es el numero de documento de i';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P44_NRO_DOC" IS 'C4P44A_¿Numero de documento de identidad?      ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P45_SEXO" IS 'C4P45_¿Es ... hombre, mujer o intersexual?     ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P46_SABE_FECHA" IS 'C4P46_¿Sabe cual es la FECHA de nacimiento?    ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P46A_DIA_NAC" IS 'C4P46A_Día de nacimiento                       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P46B_MES_NAC" IS 'C4P46B_Mes nacimiento                          ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P46C_ANO_NAC" IS 'C4P46C_Año de nacimiento                       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P47_EDAD" IS 'C4P47_¿Cuantos años cumplidos tiene?           ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P48_COLOMBIA" IS 'C4P48_¿Cuál o cuáles nacionalidades tiene ...? ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P48A_OTRA" IS 'C4P48A_¿Otra nacionalidad de...?               ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P48B_CUAL_NAL" IS 'C4P48B_¿Cual otra nacionalidad?                ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P49_PARENTESCO" IS 'C4P49_¿Cual es la relación de parentesco de ...';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P50_LUG_NAC" IS 'C4P50_¿Donde nació...?                         ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P50A_DPTO_NAC" IS 'C4P50A_Departamento de nacimiento              ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P50B_MPIO_NAC" IS 'C4P50B_Municipio de nacimiento                 ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P50C_PAIS_NAC" IS 'C4P50C_País de nacimiento                      ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P50C1_ANO_LLEGO" IS 'C4P50C1_Año en que llegó a Colombia            ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P51_RES_MAMA" IS 'C4P51_¿Cuando nació ... LA MAMA RESIDIA en:    ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P51A_DPTO_MAMA" IS 'C4P51A_Departamento donde residia la mamá al na';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P51B_MPIO_MAMA" IS 'C4P51B_Municipio donde residia la mamá al nacer';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P51C_PAIS_MAMA" IS 'C4P51C_País donde vivía la mamá al nacer       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P52_VIVIA_5ANOS" IS 'C4P52_¿En donde residia ... en Febrero de 2011 ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P52A_DPTO_5ANOS" IS 'C4P52A_Departamento donde vivía hace 5 años    ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P52B_MPIO_5ANOS" IS 'C4P52B_Municipio donde vivía hace 5 años       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P52C_PAIS_5ANO" IS 'C4P52C_País donde vivía hace 5 años            ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P52C1_ANO_LLEGA5" IS 'C4P52C1_Año en que llegó a Colombia, hace 5 año';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P53_CLASE_5ANOS" IS 'C4P53_¿El lugar donde vivia ... en Febrero de 2';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P54_VIVIA_1ANO" IS 'C4P54_¿En donde vivia ... en Febrero de 2015 (h';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P54A_DPTO_1ANO" IS 'C4P54A_Departamento donde vivía hace 1 año     ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P54B_MPIO_1ANO" IS 'C4P54B_Municipio donde vivía hace 1 año        ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P54C_PAIS_1ANO" IS 'C4P54C_País donde vivía hace 1 año             ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P55_CLASE_1ANO" IS 'C4P55_¿El lugar donde residia ... en Febrero de';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P56_CAUSA_1ANO" IS 'C4P56_¿Cual fue el MOTIVO PRINCIPAL por el que ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P56A_OTRA_CAUSA" IS 'C4P56A_¿Cual otro MOTIVO?                      ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P57_ETNIA" IS 'C4P57_¿De acuerdo con su cultura, pueblo o rasg';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P57A_COD_ETNIA" IS 'C4P57A_¿A cuál pueblo indígena pertenece ... ?(';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P58A_HABLA_LENG" IS 'C4P58A_¿Habla ... la lengua nativa de su pueblo';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P58B_OTRAS_LENG" IS 'C4P58B_¿Habla ... Otra(s) lengua(s) nativa(s)? ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P58B1_QOTRAS_LENG" IS 'C4P58B1_¿Habla ... Otra(s) lengua(s) nativa(s)?';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P58C_HABLA_ESP" IS 'C4P58C_¿Habla ... español?                     ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P59_CREENCIA" IS 'C4P59_¿Se considera:                           ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P60_AFI_SALUD" IS 'C4P60_Actualmente, ¿... se encuentra afiliado(a';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P60A_REGIMEN" IS 'C4P60A_¿A cual regimen se encuentra afiliado(a)';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P61_ENFERMO" IS 'C4P61_¿En los últimos 30 días, tuvo ... alguna ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P62A_HOSPITAL" IS 'C4P62A_¿Para tratar ese problema de salud, acud';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P62B_MED_TRAD" IS 'C4P62B_¿Para tratar ese problema de salud, acud';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P63_ATENDIERON" IS 'C4P63_¿Lo atendieron?                          ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P64A_OIR" IS 'C4P64A_Dada su condición fisica y mental, y sin';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P64B_HABLAR" IS 'C4P64B_Dada su condición fisica y mental, y sin';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P64C_VER" IS 'C4P64C_Dada su condición fisica y mental, y sin';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P64D_CAMINAR" IS 'C4P64D_Dada su condición fisica y mental, y sin';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P64E_COGER" IS 'C4P64E_Dada su condición fisica y mental, y sin';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P64F_DECIDIR" IS 'C4P64F_Dada su condición fisica y mental, y sin';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P64G_COMER" IS 'C4P64G_Dada su condición fisica y mental, y sin';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P64H_RELACION" IS 'C4P64H_Dada su condición fisica y mental, y sin';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P64I_TAREAS" IS 'C4P64I_Dada su condición fisica y mental, y sin';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P65_LIM_PPAL" IS 'C4P65_De las dificultades anteriores, ¿Cual es ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P66_CAUSA" IS 'C4P66_¿Esta dificultad fue ocasionada:         ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P66A_OTRACAUSA" IS 'C4P66A_¿Otra causa, cual?                      ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P67A_AYUDA_TEC" IS 'C4P67A_¿ Para esta dificultad ...utiliza ayudas';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P67B_AYUDA_PERS" IS 'C4P67B_¿ Para esta dificultad ... utiliza ayuda';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P67C_AYUDA_MED" IS 'C4P67C_¿ Para esta dificultad ... utiliza ayuda';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P67D_AYUDA_ANCES" IS 'C4P67D_¿ Para esta dificultad ... utiliza ayuda';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P67E_AYUDA_ANIM" IS 'C4P67E_¿ Para esta dificultad ... utiliza ayuda';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P67F_AYUDA_OTRO" IS 'C4P67F_¿ Para esta dificultad ... utiliza ayuda';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P68_CUIDA" IS 'C4P68_¿Donde o con quien permanece ... durante ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P69_ESTAB_ASIS" IS 'C4P69_¿A qué tipo de establecimiento asiste....';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P70_EDU_INTEG" IS 'C4P70_La persona con quien permanece…¿asiste o ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P71_ALFABETA" IS 'C4P71_¿... Sabe leer y escribir?               ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P72_ASISTENCIA" IS 'C4P72_¿ACTUALMENTE... asiste a algún jardín inf';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P72A_UBIC_INST" IS 'C4P72A_¿La institución a la que asiste ... está';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P72A1_DPTO_INST" IS 'C4P72A1_Departamento de institucion educativa  ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P72A2_MPIO_INST" IS 'C4P72A2_Municipio de institución educativa     ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P72A3_PAIS_INST" IS 'C4P72A3_País de institución educativa          ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P72B_DEJO_EST" IS 'C4P72B_¿Y … dejó de estudiar definitivamente?  ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP72C1_FAMILIA" IS 'C4P72C1_¿La PRINCIPAL CAUSA por la que … no asi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP72C2_ECONOMIA" IS 'C4P72C2_¿La PRINCIPAL CAUSA por la que … no asi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP72C3_INSTEDUC" IS 'C4P72C3_¿La PRINCIPAL CAUSA por la que … no asi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP72C4_EDUCANT" IS 'C4P72C4_¿La PRINCIPAL CAUSA por la que … no asi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP72C5_ENTORNOEDUC" IS 'C4P72C5_¿La PRINCIPAL CAUSA por la que … no asi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP72C6_PERSONAL" IS 'C4P72C6_¿La PRINCIPAL CAUSA por la que … no asi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP72C7_OTRA" IS 'C4P72C7_¿La PRINCIPAL CAUSA por la que … no asi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P73_NIVEL_ANOS" IS 'C4P73_¿Cuál fue el último año de estudios que .';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P74A_CEL" IS 'C4P74A_¿ ... Utiliza: Telefono Celular?        ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P74B_PC" IS 'C4P74B_¿ ... Utiliza: Computador?              ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P74C_TABLETA" IS 'C4P74C_¿ ... Utiliza: Tableta?                 ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P74D_INTERNET" IS 'C4P74D_¿ ... Utiliza: Internet?                ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P75_TRABAJO" IS 'C4P75_¿Durante LA SEMANA PASADA, ...           ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP76A_NEG_FLIA" IS 'CAP76A_Aunque ya me dijo que.... ¿la semana pas';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP76B_NEG_FLIG" IS 'CAP76B_Aunque ya me dijo que.... ¿la semana pas';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP76C_NEG_FLIF" IS 'CAP76C_Aunque ya me dijo que.... ¿la semana pas';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP76D_NEG_FLIE" IS 'CAP76D_Aunque ya me dijo que.... ¿la semana pas';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP76E_NEG_FLID" IS 'CAP76E_Aunque ya me dijo que.... ¿la semana pas';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP76F_NEG_FLIC" IS 'CAP76F_Aunque ya me dijo que.... ¿la semana pas';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP76G_NEG_FLIB" IS 'CAP76G_Aunque ya me dijo que.... ¿la semana pas';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP77_AE_EMPRESA" IS 'CAP77_¿A qué se dedica PRINCIPALMENTE la EMPRES';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP77A_AE_REALIZA" IS 'CAP77A_El código que acabó de marcar, ubíquelo ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P78_TIPO_TRAB" IS 'C4P78_¿En ese trabajo ... era?                 ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P79_SITIO_TRAB" IS 'C4P79_¿El lugar donde ... trabajó está ubicado:';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P79A_DPTO_TRAB" IS 'C4P79A_Departamento donde trabajó              ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P79B_MPIO_TRAB" IS 'C4P79B_Municipio donde trabajó                 ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P79C_PAIS_TRAB" IS 'C4P79B_País donde trabajó                      ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P80_COTIZ_PENS" IS 'C4P80_¿ ... está cotizando actualmente a un fon';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P81_EST_CIVIL" IS 'C4P81_Actualmente, ¿El estado civil de ... es? ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P82_THNV" IS 'C4P82_¿Cuantos hijos e hijas nacidos vivos ha t';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P82A_HNVH" IS 'C4P82A_Número de hombres nacidos vivos         ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P82B_HNVM" IS 'C4P82B_Número de mujeres nacidas vivas         ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P83_HNV" IS 'C4P83_De los hijos(as) que nacieron vivos de ..';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P83A_THSV" IS 'C4P83A_¿Cuantos están vivos actualmente?       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P83B_HSVH" IS 'C4P83B_Número de hombres vivos actualmente     ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P83C_HSVM" IS 'C4P83C_Número de mujeres vivas actualmente    ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P84_HFC" IS 'C4P84_¿Sabe cuantos de los hijos(as) de ... VIV';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P84A_THFC" IS 'C4P84A_¿Cuantos están fuera de Colombia?       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P84B_HFCH" IS 'C4P84B_Número de hombres fuera de Colombia     ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P84C_HFCM" IS 'C4P84C_Número de mujeres fuera de Colombia    ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P85_UHVA" IS 'C4P85_EL ULTIMO hijo(a) de ... esta vivo actual';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P86A_DIA_UHVA" IS 'C4P86A_Día de nacimiento del último hijo(a) nac';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P86B_MES_UHVA" IS 'C4P86B_Mes de nacimiento del último hijo(a) nac';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P86C_ANO_UHVA" IS 'C4P86C_Año de nacimiento del último hijo(a) nac';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP87_ORI_SEX" IS 'CAP87_¿ ... se reconoce en su orientación sexua';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."CAP88_REC_GENERO" IS 'CAP88_¿ ... se reconoce en su identidad de géne';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P89_FUE_CENS" IS 'C4P89_¿... Fue censado por el DANE en ESTE o en';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P90_LUG_CENS" IS 'C4P90_¿... donde fue censado:                  ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P90A_DPTO_CENS" IS 'C4P90A_Departamento donde fue censado          ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P90B_MPIO_CENS" IS 'C4P90B_Municipio donde fue censado             ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"."C4P91_MES_CENS" IS 'C4P91_¿En que mes fue censado?                 ';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR"  IS 'Tabla con la información de las personas que conforman el hogar';
--------------------------------------------------------
--  DDL for Table CNPV_PERSONA_RESIDENTE
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE" 
   (	"C0I1_ENCUESTA" NUMBER(9,0), 
	"C3R24_NROHOG" NUMBER(2,0), 
	"C3R38A_NRO_RESI" NUMBER(2,0), 
	"C3R38B1_1NOMBRE" VARCHAR2(15 BYTE), 
	"C3R38B2_2NOMBRE" VARCHAR2(15 BYTE), 
	"C3R38C1_1APELLIDO" VARCHAR2(15 BYTE), 
	"C3R38C2_2APELLIDO" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE"."C0I1_ENCUESTA" IS 'C0I1_Numero de Encuesta                   (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE"."C3R24_NROHOG" IS 'C3R24_Número de orden del Hogar dentro de la vi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE"."C3R38A_NRO_RESI" IS 'C3R38A_Numero de orden la persona residente    ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE"."C3R38B1_1NOMBRE" IS 'C3R38B1_Primer nombre de la persona residente  ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE"."C3R38B2_2NOMBRE" IS 'C3R38B2_Segundo nombre de la persona residente ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE"."C3R38C1_1APELLIDO" IS 'C3R38C1_Primer apellido de la persona residente';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE"."C3R38C2_2APELLIDO" IS 'C3R38C2_Segundo apellido de la persona resident';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE"  IS 'Tabla con la información de las personas residentes en el hogar';
--------------------------------------------------------
--  DDL for Table CNPV_RESULTADOS_ENTREVISTA
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA" 
   (	"C0I1_ENCUESTA" NUMBER(9,0), 
	"C3E24_NROHOG" NUMBER(2,0), 
	"CC_NRO_VIS" NUMBER(2,0), 
	"CC_HH_INI" NUMBER(2,0), 
	"CC_MM_INI" NUMBER(2,0), 
	"CC_HH_FIN" NUMBER(2,0), 
	"CC_MM_FIN" NUMBER(2,0), 
	"CC_DIA_ENT" NUMBER(2,0), 
	"CC_MES_ENT" NUMBER(2,0), 
	"CC_ANO_ENT" NUMBER(4,0), 
	"CC_RES_ENT" NUMBER(1,0), 
	"CC_COD_RECO" VARCHAR2(11 BYTE), 
	"CC_COD_SUPE" VARCHAR2(8 BYTE), 
	"TPREREG" VARCHAR2(8 CHAR), 
	"TVIVI" VARCHAR2(8 CHAR), 
	"THOGAR" VARCHAR2(8 CHAR), 
	"TPERS" VARCHAR2(8 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."C0I1_ENCUESTA" IS 'C0I1_Numero de Encuesta                   (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."C3E24_NROHOG" IS 'C3E24_Número de orden del Hogar dentro de la vi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_NRO_VIS" IS 'CC_Número de la visita                         ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_HH_INI" IS 'CC_Hora de inicio de la entrevista             ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_MM_INI" IS 'CC_Minutos de inicio de la entrevista          ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_HH_FIN" IS 'CC_Hora final de la entrevista                 ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_MM_FIN" IS 'CC_Minutos finales de la entrevista            ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_DIA_ENT" IS 'CC_Día de la entrevista                        ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_MES_ENT" IS 'CC_Mes de la entrevista                        ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_ANO_ENT" IS 'CC_Año de la entrevista                        ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_RES_ENT" IS 'CC_Resultado de la entrevista                  ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_COD_RECO" IS 'CC_Código del encuestador                      ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."CC_COD_SUPE" IS 'CC_Código del supervisor                       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."TPREREG" IS 'Tiempo Diligenciamiento Preregistro';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."TVIVI" IS 'Tiempo Diligenciamiento Vivienda';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."THOGAR" IS 'Tiempo Diligenciamiento Hogar';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"."TPERS" IS 'Tiempo Diligenciamiento Personas';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA"  IS 'Tabla con la información de resumen de la encuesta';
--------------------------------------------------------
--  DDL for Table CNPV_VIVIENDA
--------------------------------------------------------

  CREATE TABLE "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA" 
   (	"C0I1_ENCUESTA" NUMBER(9,0), 
	"C0I2_ENCPPAL" NUMBER(9,0), 
	"ID_ORIGEN" NUMBER(2,0), 
	"C1I1_DPTO" NUMBER(2,0), 
	"C1I2_MPIO" NUMBER(5,0), 
	"C1I_IDPK" NUMBER(5,0), 
	"C1I3_CLASE" NUMBER(1,0), 
	"C1I32_CPOB" NUMBER(3,0), 
	"C1I31_LOCALIDAD" NUMBER(2,0), 
	"C1I4_CO" NUMBER(4,0), 
	"C1I5_AO" NUMBER(2,0), 
	"C1I6_UC" NUMBER(6,0), 
	"C1I8_EDIFICA" NUMBER(3,0), 
	"C1I9_VIVIENDA" NUMBER(3,0), 
	"C1IV10_DIR" VARCHAR2(50 BYTE), 
	"C1IV11_BARRIO" VARCHAR2(50 BYTE), 
	"C1IV12_PARQUE_NAL" NUMBER(2,0), 
	"C1IV13_TIPOTER" NUMBER(1,0), 
	"C1IV131_CODTER" NUMBER(4,0), 
	"C1IV132_TIPO_COM" NUMBER(1,0), 
	"C1IV132A_NOM_COM" VARCHAR2(32 BYTE), 
	"C2V14_TIPO_VIV" NUMBER(1,0), 
	"C2V15_CON_OCUP" NUMBER(1,0), 
	"C2V16_TOT_HOG" NUMBER(2,0), 
	"C2V17_MAT_PARED" NUMBER(1,0), 
	"C2V18_MAT_PISO" NUMBER(1,0), 
	"C2V19_MAT_TECHO" NUMBER(1,0), 
	"C2V20_ANOS_VIV" NUMBER(1,0), 
	"C2V21A_EE" NUMBER(1,0), 
	"C2V21A1_ESTRATO" NUMBER(1,0), 
	"C2V21B_ALC" NUMBER(1,0), 
	"C2V21C_ACU" NUMBER(1,0), 
	"C2V21D_GAS" NUMBER(1,0), 
	"C2V22_TIPO_SERSA" NUMBER(1,0), 
	"C2V23_ELI_BAS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_DATOS" ;

   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C0I1_ENCUESTA" IS 'C0I1_Numero de Encuesta                   (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C0I2_ENCPPAL" IS 'C0I2_Numero de la Encuesta principal      (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."ID_ORIGEN" IS 'ID_ORIGEN_Origen de la información        (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I1_DPTO" IS 'C1I1_Departamento                         (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I2_MPIO" IS 'C1I2_Municipio                            (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I_IDPK" IS 'C1I_IDPK_Identificacion de Paquete (Centro(id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I3_CLASE" IS 'C1I3_Clase                                (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I32_CPOB" IS 'C1I32_Centro Poblado                      (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I31_LOCALIDAD" IS 'C1I31_Localidad/Comuna                    (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I4_CO" IS 'C1I4_Centro Operativo                     (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I5_AO" IS 'C1I5_Area Operativa                       (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I6_UC" IS 'C1I6_Unidad de Cobertura                  (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I8_EDIFICA" IS 'C1I8_Número de orden de la Edificación    (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1I9_VIVIENDA" IS 'C1I9_Número de orden de la Vivienda       (id) ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1IV10_DIR" IS 'C1IV10.Dirección de la Vivienda                ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1IV11_BARRIO" IS 'C1IV11_Barrio, Corregimiento o Vereda          ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1IV12_PARQUE_NAL" IS 'C1IV12_Parque Nacional natural                 ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1IV13_TIPOTER" IS 'C1IV13_Tipo de territorialidad Étnica          ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1IV131_CODTER" IS 'C1IV131_código de territorialidad Étnica       ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1IV132_TIPO_COM" IS 'C1IV132_Tipo de Comunidad, Vereda o Ranchería  ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C1IV132A_NOM_COM" IS 'C1IV132A_Nombre de la Comunidad                ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V14_TIPO_VIV" IS 'C2V14_Tipo de vivienda                         ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V15_CON_OCUP" IS 'C2V15_Condición de ocupación de la Vivienda    ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V16_TOT_HOG" IS 'C2V16_¿Cuantos Hogares hay en esta vivienda?   ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V17_MAT_PARED" IS 'C2V17_¿Cual es el material predominante de las ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V18_MAT_PISO" IS 'C2V18_¿Cual es el material predominante de los ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V19_MAT_TECHO" IS 'C2V19_¿Cual es el material predominante del TEC';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V20_ANOS_VIV" IS 'C2V20_¿Aproximadamente cuantos años de construi';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V21A_EE" IS 'C2V21A_Esta vivienda cuenta con servicio de Ene';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V21A1_ESTRATO" IS 'C2V21A1_¿Cual es el estrato de esta vivienda?  ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V21B_ALC" IS 'C2V21B_Esta vivienda cuenta con servicio de Alc';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V21C_ACU" IS 'C2V21C_Esta vivienda cuenta con servicio de Acu';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V21D_GAS" IS 'C2V21D_Esta vivienda cuenta con servicio de Gas';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V22_TIPO_SERSA" IS 'C2V22_¿El servicio sanitario (inodoro) de esta ';
   COMMENT ON COLUMN "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"."C2V23_ELI_BAS" IS 'C2V23_¿Cómo eliminan PRINCIPALMENTE la basura e';
   COMMENT ON TABLE "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA"  IS 'Tabla con la información de la vivienda encuestada';
--------------------------------------------------------
--  DDL for Index CNP_DOMINIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."CNP_DOMINIO_PK" ON "CNP_INSCRIPCION_WEB"."CNP_DOMINIO" ("ID_DOMINIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index PK_CNPV_PERSONA_RESIDENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."PK_CNPV_PERSONA_RESIDENTE" ON "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE" ("C0I1_ENCUESTA", "C3R24_NROHOG", "C3R38A_NRO_RESI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index PK_CNPV_PERSONA_FALLECIDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."PK_CNPV_PERSONA_FALLECIDA" ON "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA" ("C0I1_ENCUESTA", "C3F24_NROHOG", "C3F35A_NRO_FALL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index CNPV_ENCUESTA_FINAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL_PK" ON "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL" ("NRO_ENCUESTA_FORM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index CNPV_ADMIN_CONTROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL_PK" ON "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL" ("NRO_ENCUESTA_FORM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index PK_PREREGISTRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."PK_PREREGISTRO" ON "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO" ("CEDULA", "C4P40_TIPO_DOC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index PK_CNPV_RESULTADOS_ENTREVISTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."PK_CNPV_RESULTADOS_ENTREVISTA" ON "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA" ("C0I1_ENCUESTA", "C3E24_NROHOG", "CC_NRO_VIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index PK_CNPV_HOGAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."PK_CNPV_HOGAR" ON "CNP_INSCRIPCION_WEB"."CNPV_HOGAR" ("C0I1_ENCUESTA", "C3H24_NROHOG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index PK_CNPV_PERSONA_HOGAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."PK_CNPV_PERSONA_HOGAR" ON "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR" ("C0I1_ENCUESTA", "C3P24_NROHOG", "C4P41_NRO_PER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index CNPV_PARAM_ESTADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."CNPV_PARAM_ESTADOS_PK" ON "CNP_INSCRIPCION_WEB"."CNPV_PARAM_ESTADOS" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index CNP_PREREGISTRO_PERSONAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS_PK" ON "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS" ("C4P40_TIPO_DOC", "C4P41_SABE_DOC", "DIRECTORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index CNP_ADMIN_USUARIOS_ADM_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM_UK1" ON "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index PK_RESPUESTA_DOMINIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."PK_RESPUESTA_DOMINIO" ON "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO" ("ID_RESPUESTA_DOMINIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index CNP_ADMIN_USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_PK" ON "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS" ("NRO_ENCUESTA_FORM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index CNPV_PARAM_MUESTRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA_PK" ON "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index CNP_ADMIN_USUARIOS_ADM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM_PK" ON "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" ("ID_USUARIOS_ADM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  DDL for Index PK_CNPV_VIVIENDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNP_INSCRIPCION_WEB"."PK_CNPV_VIVIENDA" ON "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA" ("C0I1_ENCUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND" ;
--------------------------------------------------------
--  Constraints for Table CNP_DOMINIO
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_DOMINIO" ADD CONSTRAINT "CNP_DOMINIO_PK" PRIMARY KEY ("ID_DOMINIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_DOMINIO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_DOMINIO" MODIFY ("ID_DOMINIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNP_RESPUESTA_DOMINIO
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO" ADD CONSTRAINT "PK_RESPUESTA_DOMINIO" PRIMARY KEY ("ID_RESPUESTA_DOMINIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO" MODIFY ("VALOR_MINIMO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO" MODIFY ("ID_DOMINIO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO" MODIFY ("ID_RESPUESTA_DOMINIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNP_ADMIN_USUARIOS_ADM
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" ADD CONSTRAINT "CNP_ADMIN_USUARIOS_ADM_UK1" UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" ADD CONSTRAINT "CNP_ADMIN_USUARIOS_ADM_PK" PRIMARY KEY ("ID_USUARIOS_ADM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" MODIFY ("TIPO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS_ADM" MODIFY ("ID_USUARIOS_ADM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNPV_PARAM_ESTADOS
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_ESTADOS" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_ESTADOS" ADD CONSTRAINT "CNPV_PARAM_ESTADOS_PK" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CNP_PREREGISTRO_PERSONAS
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO_PERSONAS" ADD PRIMARY KEY ("DIRECTORIO", "C4P40_TIPO_DOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CNPV_PERSONA_RESIDENTE
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE" ADD CONSTRAINT "PK_CNPV_PERSONA_RESIDENTE" PRIMARY KEY ("C0I1_ENCUESTA", "C3R24_NROHOG", "C3R38A_NRO_RESI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CNPV_PARAM_PAIS
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_PAIS" ADD PRIMARY KEY ("ID_PAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_PAIS" MODIFY ("ID_PAIS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNPV_PARAM_CATEGORIAS
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_CATEGORIAS" ADD PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_CATEGORIAS" MODIFY ("DESCRIPCION_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_CATEGORIAS" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNPV_ADMIN_CONTROL
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL" ADD CONSTRAINT "CNPV_ADMIN_CONTROL_PK" PRIMARY KEY ("NRO_ENCUESTA_FORM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL" MODIFY ("FK_MPIO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL" MODIFY ("FK_DEPTO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL" MODIFY ("FK_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL" MODIFY ("NRO_ENCUESTA_FORM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNP_PREREGISTRO
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_PREREGISTRO" ADD CONSTRAINT "PK_PREREGISTRO" PRIMARY KEY ("CEDULA", "C4P40_TIPO_DOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CNPV_RESULTADOS_ENTREVISTA
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA" ADD CONSTRAINT "PK_CNPV_RESULTADOS_ENTREVISTA" PRIMARY KEY ("C0I1_ENCUESTA", "C3E24_NROHOG", "CC_NRO_VIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA" MODIFY ("CC_NRO_VIS" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA" MODIFY ("C3E24_NROHOG" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA" MODIFY ("C0I1_ENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNPV_PERSONA_HOGAR
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR" ADD CONSTRAINT "PK_CNPV_PERSONA_HOGAR" PRIMARY KEY ("C0I1_ENCUESTA", "C3P24_NROHOG", "C4P41_NRO_PER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CNP_ADMIN_USUARIOS
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS" MODIFY ("NRO_ENCUESTA_FORM" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS" ADD CONSTRAINT "CNP_ADMIN_USUARIOS_PK" PRIMARY KEY ("NRO_ENCUESTA_FORM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS" MODIFY ("TIPO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_ADMIN_USUARIOS" MODIFY ("USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNPV_PARAM_MUESTRA
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA" ADD CONSTRAINT "CNPV_PARAM_MUESTRA_PK" PRIMARY KEY ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA" MODIFY ("CEDULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNPV_ENCUESTA_FINAL
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL" ADD CONSTRAINT "CNPV_ENCUESTA_FINAL_PK" PRIMARY KEY ("NRO_ENCUESTA_FORM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL" MODIFY ("NRO_ENCUESTA_FORM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNPV_VIVIENDA
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA" ADD CONSTRAINT "PK_CNPV_VIVIENDA" PRIMARY KEY ("C0I1_ENCUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA" MODIFY ("C0I1_ENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CNPV_HOGAR
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_HOGAR" ADD CONSTRAINT "PK_CNPV_HOGAR" PRIMARY KEY ("C0I1_ENCUESTA", "C3H24_NROHOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CNPV_PERSONA_FALLECIDA
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA" ADD CONSTRAINT "PK_CNPV_PERSONA_FALLECIDA" PRIMARY KEY ("C0I1_ENCUESTA", "C3F24_NROHOG", "C3F35A_NRO_FALL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CNP_INS_WEB_IND"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CNP_RESPUESTA_DOMINIO
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNP_RESPUESTA_DOMINIO" ADD CONSTRAINT "FK_DOM_ID_DOMINIO" FOREIGN KEY ("ID_DOMINIO")
	  REFERENCES "CNP_INSCRIPCION_WEB"."CNP_DOMINIO" ("ID_DOMINIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CNPV_ADMIN_CONTROL
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL" ADD CONSTRAINT "FK_ADMINCONTROL_ESTADOS" FOREIGN KEY ("FK_ESTADO")
	  REFERENCES "CNP_INSCRIPCION_WEB"."CNPV_PARAM_ESTADOS" ("ID_ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CNPV_ENCUESTA_FINAL
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_ENCUESTA_FINAL" ADD CONSTRAINT "CNPV_ENCUESTA_FINAL_CNPV__FK1" FOREIGN KEY ("NRO_ENCUESTA_FORM")
	  REFERENCES "CNP_INSCRIPCION_WEB"."CNPV_ADMIN_CONTROL" ("NRO_ENCUESTA_FORM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CNPV_HOGAR
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_HOGAR" ADD CONSTRAINT "FK_C0I1_ENCUESTA" FOREIGN KEY ("C0I1_ENCUESTA")
	  REFERENCES "CNP_INSCRIPCION_WEB"."CNPV_VIVIENDA" ("C0I1_ENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CNPV_PARAM_MUESTRA
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PARAM_MUESTRA" ADD FOREIGN KEY ("CATEGORIA")
	  REFERENCES "CNP_INSCRIPCION_WEB"."CNPV_PARAM_CATEGORIAS" ("ID_CATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CNPV_PERSONA_FALLECIDA
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_FALLECIDA" ADD CONSTRAINT "FK_C0I1_ENCUESTA_C3H24_NROHOG" FOREIGN KEY ("C0I1_ENCUESTA", "C3F24_NROHOG")
	  REFERENCES "CNP_INSCRIPCION_WEB"."CNPV_HOGAR" ("C0I1_ENCUESTA", "C3H24_NROHOG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CNPV_PERSONA_HOGAR
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_HOGAR" ADD CONSTRAINT "FK_C0I1_ENCUESTA_C3P24_NROHOG" FOREIGN KEY ("C0I1_ENCUESTA", "C3P24_NROHOG")
	  REFERENCES "CNP_INSCRIPCION_WEB"."CNPV_HOGAR" ("C0I1_ENCUESTA", "C3H24_NROHOG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CNPV_PERSONA_RESIDENTE
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_PERSONA_RESIDENTE" ADD CONSTRAINT "FK_C0I1_ENCUESTA_C3R24_NROHOG" FOREIGN KEY ("C0I1_ENCUESTA", "C3R24_NROHOG")
	  REFERENCES "CNP_INSCRIPCION_WEB"."CNPV_HOGAR" ("C0I1_ENCUESTA", "C3H24_NROHOG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CNPV_RESULTADOS_ENTREVISTA
--------------------------------------------------------

  ALTER TABLE "CNP_INSCRIPCION_WEB"."CNPV_RESULTADOS_ENTREVISTA" ADD CONSTRAINT "FK_C0I1_ENCUESTA_C3E24_NROHOG" FOREIGN KEY ("C0I1_ENCUESTA", "C3E24_NROHOG")
	  REFERENCES "CNP_INSCRIPCION_WEB"."CNPV_HOGAR" ("C0I1_ENCUESTA", "C3H24_NROHOG") ENABLE;
--------------------------------------------------------
--  DDL for Function FC_CALCULASEMANAANTERIOR
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CNP_INSCRIPCION_WEB"."FC_CALCULASEMANAANTERIOR" RETURN VARCHAR2 AS 
 p_fecha date := sysdate;
 v_fecha date ;
 v_dia   number := 0;
BEGIN
  select p_fecha-7 into v_fecha from dual;
  dbms_output.put_line (to_char(v_fecha));
  select to_number(to_char (v_fecha , 'D')) into  v_dia from dual;
  dbms_output.put_line (v_dia);
  while v_dia > 1 loop
     v_fecha := v_fecha - 1  ;
     select to_number(to_char (v_fecha , 'D')) into  v_dia from dual;
  END LOOP;
  dbms_output.put_line (to_char(v_fecha + 1));
  dbms_output.put_line (to_char(v_fecha + 5));
  RETURN (to_char(v_fecha + 1)||','||to_char(v_fecha + 5));
END FC_CALCULASEMANAANTERIOR;

/

